export const TRANSLATION_PIPELINE = [
    "zh",    // Simplified Chinese
    "ar",    // Arabic
    "ru",    // Russian
    "am",    // Amharic
    "sw",    // Swahili
    "uk",    // Ukrainian
    "fr",    // French
    "ja",    // Japanese
    "es",    // Spanish
    "tr",    // Turkish
    "bn",    // Bengali
    "vi",    // Vietnamese
    "pl",    // Polish
    "it",    // Italian
    "cs",    // Czech
    "pt",    // Portuguese
    "ml",    // Malayalam
    "sr",    // Serbian
    "id",    // Indonesian
    "hu",    // Hungarian
    "nl",    // Dutch
    "sv",    // Swedish
    "hi",    // Hindi
    "th",    // Thai
    "el",    // Greek
    "bg",    // Bulgarian
    "ro",    // Romanian
    "az",    // Azerbaijani
    "km",    // Khmer
    "my",    // Burmese
    "ur",    // Urdu
    "da",    // Danish
    "fi",    // Finnish
    "sk",    // Slovak
    "no",    // Norwegian
    "ca",    // Catalan
    "lt",    // Lithuanian
    "lv",    // Latvian
    "sl",    // Slovenian
    "gl",    // Galician
    "zu",    // Zulu
    "xh",    // Xhosa
    "tt",    // Tatar
    "mn",    // Mongolian
    "ga",    // Irish
    "ko",    // Korean
    "sq",    // Albanian
    "hr",    // Croatian
    "mk",    // Macedonian
    "et",    // Estonian
    "ne",    // Nepali
    "la",    // Latin
    "is",    // Icelandic
    "cy",    // Welsh
    "tl",    // Tagalog
    "te",    // Telugu
    "pa",    // Punjabi
    "mr",    // Marathi
    "si",    // Sinhala
    "oc",    // Occitan
    "ka",    // Georgian
    "eu",    // Basque
    "hy",    // Armenian
    "bs",    // Bosnian
    "ht",    // Haitian Creole
    "ky",    // Kyrgyz
    "lo",    // Lao
    "tk",    // Turkmen
    "rw",    // Kinyarwanda
    "so",    // Somali
    "haw",   // Hawaiian
    "jv",    // Javanese
    "be",    // Belarusian
];
