export const TRANSLATION_PIPELINE = [
    "ab",    // Abkhaz
    "zh",    // Chinese (Simplified)
    "sw",    // Swahili
    "fi",    // Finnish
    "ar",    // Arabic
    "ja",    // Japanese
    "zu",    // Zulu
    "tr",    // Turkish
    "he",    // Hebrew
    "vi",    // Vietnamese
    "is",    // Icelandic
    "yo",    // Yoruba
    "th",    // Thai
    "ru",    // Russian
    "ms",    // Malay
    "el",    // Greek
    "am",    // Amharic
    "es",    // Spanish
    "km",    // Khmer
    "no",    // Norwegian
    "pa",    // Punjabi
    "ko",    // Korean
    "ha",    // Hausa
    "fr",    // French
    "hi",    // Hindi
    "hu",    // Hungarian
    "so",    // Somali
    "it",    // Italian
    "ta",    // Tamil
    "pl",    // Polish
    "ig",    // Igbo
    "sv",    // Swedish
    "bn",    // Bengali
    "sr",    // Serbian
    "id",    // Indonesian
    "uk",    // Ukrainian
    "pt",    // Portuguese
    "mn",    // Mongolian
    "sk",    // Slovak
    "rw",    // Kinyarwanda
    "nl",    // Dutch
    "ga",    // Irish
    "az",    // Azerbaijani
    "st",    // Sesotho
    "ml",    // Malayalam
    "cs",    // Czech
    "lt",    // Lithuanian
    "ro",    // Romanian
    "ps",    // Pashto
    "lv",    // Latvian
    "da",    // Danish
    "ne",    // Nepali
    "bg",    // Bulgarian
    "ur",    // Urdu
    "et",    // Estonian
    "my",    // Burmese
    "mt",    // Maltese
    "lo",    // Lao
    "eu",    // Basque
    "sq",    // Albanian
    "tn",    // Tswana
    "ka",    // Georgian
    "be",    // Belarusian
    "sm",    // Samoan
    "gd",    // Scots Gaelic
    "fa",    // Persian
    "af",    // Afrikaans
    "si",    // Sinhala
    "sl",    // Slovenian
    "tt",    // Tatar
    "mr",    // Marathi
    "lb",    // Luxembourgish
    "de",    // German
    "te",    // Telugu
    "sn",    // Shona
    "luo",   // Luo
    "ss",    // Swati
    "jw",    // Javanese
    "ckb",   // Kurdish (Sorani)
    "ak",    // Twi (Akan)
    "qu",    // Quechua
    "ln",    // Lingala
    "sd",    // Sindhi
    "rn",    // Rundi
    "ff",    // Fulfulde
    "ny",    // Chichewa (Nyanja)
    "xh",    // Xhosa
    "yi",    // Yiddish
    "yua",   // Yucatec Maya
];
